export const content = {
  header: {
    logo: '/assets/img/logo.png',
    text: 'SHREE HALARI VISA OSWAL SAMAJ, AHMEDABAD',
  },
  footer: {
    addressText1: 'C/o. Bunglow No. 29, Somnathnagar Society',
    addressText2: 'Opp. Ambica Hardware, Vijaynagar Road, Naranpura, Ahmedabad - 380013',
    email: 'hvosamd2020@gmail.com',
    mobile1: '9727798789',
    mobile2: '9426994276',
  },
  title: {
    appTitle: 'JAI JINENDRA 🙏',
    createPageTitle: 'Add Family Information',
    viewPageTitle: 'View Family Information',
    updatePageTitle: 'Update Family Information',
  },
  subTitle: {
    mainMemberDetails: 'Main Member Details',
    familyMember: 'Family Member',
    addMember: 'Add a Member',
    updateMember: 'Update a Member',
    viewMember: 'View Members',
  },
  stepper: {
    step1: 'Step 1',
    step2: 'Step 2',
  },
  buttonsText: {
    addMember: 'Add Members',
    next: 'Next',
    back: 'Back',
    submit: 'Submit',
  },
  fallbackText: {
    loadingText: 'Loading Options Please Wait ...',
  },
  forms: {
    selectOption: 'Please Select Any Option',
    select: 'Select',
    village: 'Village',
    email: 'Email',
    residentialAddress: 'Residential Address',
    city: 'City',
    officeAddress: 'Office Address',
    mainMemberName: 'Main Member Name',
    fullName: 'fullName',
    firstName: 'First Name',
    middleName: 'Middle Name',
    lastName: 'Surname (Original Surname)',
    relation: 'Relation To Main Member',
    dateOfBirth: 'Date Of Birth',
    age: 'Age',
    bloodGroup: 'Blood Group',
    maritialStatus: 'Marital Status',
    education: 'Education',
    marriageDate: 'Marriage Date',
    contactNumber: 'Contact Number',
    alternateContact: 'Alternate Contact Number',
    createdAt: 'Created At',
    profilePic: 'Profile Picture',
    constraint: 'PNG, JPG, GIF up to 10MB',
  },
  message: {
    savingYourData: 'Saving Your Data..',
    detailSaved: 'Details Saved Sucessfully',
  },
  pages: {
    homePage: 'Home Page',
  },
};
